blog/urls.py
from django.urls import path, re_path
from blog.views import MainView
from blog.views import TagsView
from blog.views import TypesView
from blog.views import MzView

app_name = 'blog'
urlpatterns = [
    re_path(r'^$', MainView.as_view(), name='home'),
    re_path('^tags/(?P<tag_id>\w+)/$', TagsView.as_view(), name='tags'),
    re_path('^types/(?P<type_id>\w+)/$', TypesView.as_view(), name='types'),
    re_path(r'^mz/$', MzView.as_view(), name='mz'),
]

blog_user/urls.py
from django.urls import path, re_path
from blog_user.views import SigninView, SignupView

app_name = 'blog_user'
urlpatterns = [
    re_path(r'^signin/$', SigninView.as_view(), name='signin'),
    re_path(r'^signup/$', SignupView.as_view(), name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from mysite import settings;

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'', include('blog.urls', namespace='blog')),
    re_path(r'article/', include('blog_article.urls', namespace='article')),
    re_path(r'user/', include('blog_user.urls', namespace='user')),
]

blog/models.py
from django.db import models

blog/views.py
from django.views.generic.list import ListView
from django.views.generic import DetailView
from blog_user.models import BUser
from blog_article.models import Article, ArticleTag, ArticleType
from blog import conf
from blog import const
from django.db.models import Q


# base mixin
class BaseMixin(object):
    def get_context_data(self, **kwargs):
        context = super(BaseMixin, self).get_context_data(**kwargs)
        tags = ArticleTag.objects.order_by('order')
        # 全局所有 tag 类型
        context['tags'] = tags
        # 导航 tags 对应的默认 tag 类型
        if len(tags) > 0:
            context['nav_tag'] = tags.filter(tag_id=const.TAG_NAV_ID)[0]
        else:
            context['nav_tag'] = None

        # 全局所有 type 类型
        types = ArticleType.objects.order_by('order')
        # 全局所有 tag 类型
        context['types'] = types
        # 导航 types 对应的默认 type 类型
        if len(types) > 0:
            context['nav_type'] = types.filter(type_id=const.TYPE_NAV_ID)[0]
        else:
            context['nav_type'] = None

        # 当前作者信息
        context['author'] = BUser.objects.get(is_author=True)
        return context


# home view
class MainView(BaseMixin, ListView):
    model = Article
    template_name = "blog/index.html"
    paginate_by = conf.MAIN_PAGE_NUM

    def get_queryset(self):
        at = ArticleType.objects.get(type_id=const.TYPE_MZ_ID)
        return Article.objects.all().filter(~Q(type_id=at.id)).order_by('-create_time')


# types view
class TypesView(BaseMixin, ListView):
    model = Article
    template_name = 'blog/type.html'
    paginate_by = conf.MAIN_PAGE_NUM

    def get_queryset(self):
        tid = self.kwargs.get('type_id', '')
        at = ArticleType.objects.get(type_id=tid)
        return Article.objects.all().filter(type_id=at.id).order_by('-create_time')

    def get_context_data(self, **kwargs):
        context = super(TypesView, self).get_context_data(**kwargs)
        # 当前选择的类型
        tid = self.kwargs.get('type_id', '')
        context['select_type'] = ArticleType.objects.get(type_id=tid)
        return context


# tags view
class TagsView(BaseMixin, ListView):
    model = Article
    template_name = 'blog/tags.html'
    paginate_by = conf.MAIN_PAGE_NUM

    def get_queryset(self):
        tag = self.kwargs.get('tag_id', '')
        return Article.objects.all().filter(tags__tag_id=tag).order_by('-create_time')

    def get_context_data(self, **kwargs):
        context = super(TagsView, self).get_context_data(**kwargs)
        # 当前选择的标签
        context['select_tag'] = self.kwargs.get('tag_id', '')
        return context


# mz view
class MzView(BaseMixin, ListView):
    model = Article
    template_name = "blog/mz.html"

    def get_queryset(self):
        at = ArticleType.objects.get(type_id=const.TYPE_MZ_ID)
        return Article.objects.all().filter(type_id=at.id).order_by('-create_time')

    def get_context_data(self, **kwargs):
        context = super(MzView, self).get_context_data(**kwargs)
        self.get_group_list(context)
        return context

    # 获取分组
    def get_group_list(self, context):

        index = 0
        round2 = 0
        round3 = 0
        round4 = 0

        temps2_1 = []
        temps2_2 = []

        temps3_1 = []
        temps3_2 = []
        temps3_3 = []

        temps4_1 = []
        temps4_2 = []
        temps4_3 = []
        temps4_4 = []
        for item in self.object_list:
            index += 1

            # 2
            if index % 2 == 0:
                round2 += 1

            if index - round2 * 2 == 1:
                temps2_1.append(item)
            elif index - round2 * 2 == 0:
                temps2_2.append(item)

            # 3
            if index % 3 == 0:
                round3 += 1

            if index - round3 * 3 == 1:
                temps3_1.append(item)
            elif index - round3 * 3 == 2:
                temps3_2.append(item)
            elif index - round3 * 3 == 0:
                temps3_3.append(item)

            # 4
            if index % 4 == 0:
                round4 += 1

            if index - round4 * 4 == 1:
                temps4_1.append(item)
            elif index - round4 * 4 == 2:
                temps4_2.append(item)
            elif index - round4 * 4 == 3:
                temps4_3.append(item)
            elif index - round4 * 4 == 0:
                temps4_4.append(item)

        context['group_2_1'] = temps2_1
        context['group_2_2'] = temps2_2

        context['group_3_1'] = temps3_1
        context['group_3_2'] = temps3_2
        context['group_3_3'] = temps3_3

        context['group_4_1'] = temps4_1
        context['group_4_2'] = temps4_2
        context['group_4_3'] = temps4_3
        context['group_4_4'] = temps4_4

blog/templates/blog/base/article.html
<div class="fh-article-view clearfix">
   <div class="fh-article-title-view">
       <div class="fh-article-subtitle-view pull-left visible-lg visible-md visible-sm">
            <div class="fh-article-subtitle">
               <span>{{ article.type.name }}</span>
           </div>
           <div class="fh-artucle-subtitle-arrow"></div>
       </div>
       <a class="fh-article-title h2" href="/article/{{ article.id }}">{{ article.title }}</a>
    </div>
    <div class="row fh-article-tag-view">
       <div class="fh-article-data-view pull-left">
           <span class="label glyphicon glyphicon-calendar">
               <spqn class="fh-article-data">{{ article.create_time | date:"Y-m-d" }}</spqn>
           </span>
           <span class="label glyphicon glyphicon glyphicon-comment">
               <span class="fh-article-data">{{ article.comments_num }}</span>
           </span>
           <span class="label glyphicon glyphicon-eye-open">
               <span class="fh-article-data">{{ article.browse_num }}</span>
           </span>
       </div>
       <div class="fh-article-tag pull-right visible-lg visible-md visible-sm">
           {% for tag in article.tags.all %}
               {% if tag.get_is_none %}
               {% else %}
                   <span class="label {{ tag.tag_label_style }}">{{ tag.name }}</span>
               {% endif %}
           {% endfor %}
       </div>
   </div>
    <hr>
    <div class="row fh-article-abstract-view">
        <div class="fh-article-img col-lg-4 col-md-4 col-sm-4">
            <div class="thumbnail">
                <a href="/article/{{ article.id }}">
                    <img src={{ article.img }}>
                </a>
            </div>
        </div>
        <div class="fh-article-abstract col-lg-8 col-md-8 col-sm-8">
            <a href="/article/{{ article.id }}">
                <p>
                    {{ article.abstract }}
                </p>
            </a>
        </div>
    </div>
   `<hr>
</div>

blog/templates/blog/base/article_paging.html
{% if object_list %}
    {% if page_obj.has_previous or page_obj.has_next %}
        <nav aria-label="...">
            <ul class="pager">
                {% if  page_obj.has_previous %}
                    <li class="previous"><a href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&larr;</span> Previous</a></li>
                {% else %}
                    <li class="previous disabled"><a class="disabled"><span aria-hidden="true">&larr;</span> Previous</a></li>
                {% endif %}

                {% if  page_obj.has_next %}
                    <li class="next"><a href="?page={{ page_obj.next_page_number }}">Next <span aria-hidden="true">&rarr;</span></a></li>
                {% else %}
                    <li class="next disabled"><a class="disabled">Next <span aria-hidden="true">&rarr;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endif %}

blog/templates/blog/base/author.html
<div class="fh-author-view">
    <div class="fh-author-tag-view">
        <hr>
        <a href="/types/{{ nav_type.type_id }}">FEATURED TYPES</a>
        <div class="row fh-author-tag">
            {% for type in types %}
                <a href="/types/{{ type.type_id }}" class="btn btn-default btn-sm">{{ type.name }}</a>
            {% endfor %}
        </div>

        <hr>
        <a href="/tags/{{ nav_tag.tag_id }}">FEATURED TAGS</a>
        <div class="row fh-author-tag">
            {% for tag in tags %}
                {% if tag.get_is_none %}
                {% else %}
                    <a href="/tags/{{ tag.tag_id }}" class="btn btn-default btn-sm">{{ tag.name }}</a>
                {% endif %}
            {% endfor %}
        </div>
        <hr>
    </div>
    <div class="fh-author-me-view">
        <a href="about">ABOUT ME</a>
        <div class="fh-author-me-head">
            <img src="{{ author.head }}" alt="" width="162" height="150">
        </div>
        <div class="fh-author-me-info">
            <p>
                {{ author.introduction }}
            </p>
        </div>
    </div>
</div>

blog/templates/blog/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
         <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
        <title>Fasthro | Blog</title>

        <!-- Bootstrap -->
        <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}">
        <link href="{% static "css/blog.css" %}" rel="stylesheet">
        {% block css %} {% endblock %}
        {% block head-js %} {% endblock %}
        <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
        <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
        <!--[if lt IE 9]>
          <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
  </head>
  <body>
    <div class="fh-main">
        {% block main-nav %}{% endblock %}
        {% block jumbotron %} {% endblock %}
        {% block main %} {% endblock %}
    </div>
    {% block main-footer %}{% endblock %}
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="{% static "jquery/jquery-3.2.1.min.js" %}"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>

    {% block js %} {% endblock %}
  </body>
</html>

blog/templates/blog/base/footer.html
<footer>
    <div class="main-footer">
        <span>基于Django 和 Bootstrap 搭建的博客系统</span>
    </div>
</footer>

blog/templates/blog/base/mz-article.html
{% load static %}

<div class="mz-item-view">
    <div class="mz-kong"></div>
    <a href="/article/{{ article.id }}">
        <div class="mz-item-wrap">
            <div class="mz-item-icon-wrap">
                <img class="mz-item-icon" src="{{ article.img }}">
            </div>
            <div class="mz-item-content">
                <div class="mz-item-title">
                    <b>{{ article.title }}</b>
                </div>
                <div class="mz-item-content-kong"></div>
                <div class="mz-item-abstract">
                    <p>{{ article.abstract }}</p>
                </div>
            </div>
            <div class="mz-item-time">
                <b>{{ article.create_time | date:"Y-m-d" }}</b>
            </div>
        </div>
    </a>
</div>

blog/templates/blog/base/nav.html
<nav class="navbar navbar-fixed-top fh-navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed fh-navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar fh-icon-bar"></span>
                <span class="icon-bar fh-icon-bar"></span>
                <span class="icon-bar fh-icon-bar"></span>
            </button>
            <div class="fh-navbar-brand">
                <a href="{% url 'blog:home' %}" class="fh-navbar-logo"><strong>FAST HRO</strong></a>
                <img src="../../../static/img/blog-logo.png" alt="" class="fh-navbar-logo-icon" height="24px">
            </div>
        </div>
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="navbar-nav navbar-right fh-navbar-nav">
                <li class="fh-nav-btn"><a href="{% url 'blog:home' %}"><strong>HOME</strong></a></li>
                <li class="fh-nav-btn"><a href="/types/{{ nav_type.type_id }}"><strong>TYPES</strong></a></li>
                <li class="fh-nav-btn"><a href="/tags/{{ nav_tag.tag_id }}"><strong>TAGS</strong></a></li>
                <li class="fh-nav-btn"><a href="{% url 'blog:mz' %}"><strong>MZ</strong></a></li>
                <li class="fh-nav-btn"><a href="about"><strong>ABOUT</strong></a></li>
                <li class="fh-nav-btn" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-user"></span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu fh-dropdown-menu">
                        <li class="fh-nav-dropdown-menu-btn"><a href="{% url 'user:signin' %}">Sign In</a></li>
                        <li class="fh-nav-dropdown-menu-btn"><a href="{% url 'user:signup' %}">Sign Up</a></li>
                    </ul>
                </li>
            </ul>
         </div>
    </div>
</nav>